name: step_it_up
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.0
  dio: ^5.2.1+1
  jwt_decoder:
    git:
      url: https://github.com/gustavo0197/dart-jwt-decoder
      ref: master
  logger: ^1.1.0
  equatable: ^2.0.5
  flutter_zoom_drawer: ^3.1.1
  intl: ^0.18.1
  page_view_dot_indicator: ^2.1.0
  carousel_slider: ^4.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/default_profile_picture.jpg
    - assets/trophy_icon.png
    - assets/app_logo.png
    - assets/app_icon.png
    - assets/login_header.png
    - assets/warning_icon.png
    - assets/fitbit_device.png
    - assets/garmin_device.png
    - assets/google_device.png
    - assets/mi_device.png
    - assets/samsung_device.png